---
- name: Fail if Operating System is not Supported
  fail:
    msg: "Minimum Operating System Version Ubuntu 16.04"
  when:
    - ansible_distribution != 'Ubuntu'
    - ansible_distribution_major_version | int >= 16

- name: Get Service Init Status
  stat:
    path: /sbin/init
  register: service_init_status

- name: Set Host Facts
  set_fact:
    uninstall_iscsi-lio: "{{ uninstall_iscsi-lio | default(default_value, true) }}"
    uninstall_nfs: "{{ uninstall_nfs | default(default_value, true) }}"
