---
- name: Reload ISCSI LIO Service
  systemd:
    daemon_reload: yes
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk

- name: Get ISCSI LIO Service Info
  shell: service target status | grep not-found || true
  args:
    warn: false
  register: iscsi-lio_service_info
  when:
    - service_init_status.stat.exists

- name: Enable ISCSI LIO Service
  service:
    name: target
    enabled: yes
    state: restarted
  when:
    - iscsi-lio_service_info.stdout.find("not-found") == -1
